apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: tls-connection-certificate-not-setup
  labels:
    category: "Platform & Infrastructure Security"
    severity: critical
spec:
  id: SPOTTER-PLATFORM-INFRASTRUCTURE-SECURITY-127
  name: "TLS Connection Certificate Not Setup"
  version: "1.0.0"
  description: "The API server should be configured with TLS certificate and key files for secure communication."
  severity:
    level: CRITICAL
    score: 9.8
  category: "Platform & Infrastructure Security"
  subcategory: "API Server TLS"
  cwe: "CWE-295"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "1.2.10"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
        versions:
          - "v1"
        kinds:
          - Pod
  cel: |
    has(object.spec.containers) && object.spec.containers.exists(c, has(c.command) && c.command.exists(cmd, cmd == "kube-apiserver") && (!has(c.args) || !c.args.exists(arg, arg.startsWith("--tls-cert-file=")) || !c.args.exists(arg, arg.startsWith("--tls-private-key-file="))))
  remediation:
    manual: "Ensure that --tls-cert-file and --tls-private-key-file flags are set for the kube-apiserver."
  references:
    - title: "Kubernetes API Server Flags"
      url: "https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-30"
