apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: workload-host-port-not-specified
  labels:
    category: "Platform & Infrastructure Security"
    severity: high
spec:
  id: SPOTTER-PLATFORM-INFRASTRUCTURE-SECURITY-006
  name: "Workload Host Port Not Specified"
  version: "1.0.0"
  description: "Binding a pod to a hostIP without hostPort can create security vulnerabilities."
  severity:
    level: HIGH
    score: 7.9
  category: "Platform & Infrastructure Security"
  subcategory: "Pod Security"
  cwe: "CWE-605"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.2.4"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - "apps"
        versions:
          - "v1"
        kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    (object.kind == 'Pod' && has(object.spec.containers) && object.spec.containers.exists(c, has(c.ports) && c.ports.exists(p, has(p.hostIP) && !has(p.hostPort)))) ||
    (object.kind != 'Pod' && has(object.spec.template.spec.containers) && object.spec.template.spec.containers.exists(c, has(c.ports) && c.ports.exists(p, has(p.hostIP) && !has(p.hostPort))))
  remediation:
    manual: "If you are using hostIP, make sure you have hostPorts. Use services to expose applications."
  references:
    - title: "Pod Security Standards"
      url: "https://kubernetes.io/docs/concepts/security/pod-security-standards/#host-namespaces"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
