apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: image-tag-is-latest
  labels:
    category: "Supply Chain & Image Security"
    severity: high
spec:
  id: SPOTTER-SUPPLY-CHAIN-IMAGE-SECURITY-619
  name: "Image Tag Is Latest"
  version: "1.0.0"
  description: "Containers must not use 'latest' tag"
  severity:
    level: HIGH
    score: 8.0
  category: "Supply Chain & Image Security"
  subcategory: "Image Pinning"
  cwe: "CWE-619"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "4.1.4"
  match:
    resources:
      kubernetes:
        apiGroups:
        - ''
        - apps
        versions:
        - v1
        kinds:
        - Pod
        - Deployment
        namespaces:
          include:
          - '*'
          exclude:
          - kube-system
          - kube-public
  cel: |
    (object.kind == 'Pod' && has(object.spec.containers) && object.spec.containers.exists(c, has(c.image) && c.image.endsWith(":latest"))) ||
    (object.kind != 'Pod' && has(object.spec.template.spec.containers) && object.spec.template.spec.containers.exists(c, has(c.image) && c.image.endsWith(":latest")))
  remediation:
    manual: "Pin exact image tags or digests"
  metadata:
    author: "Spotter AutoGen"
    created: "2025-07-29"