openapi: 3.0.3
info:
  title: Spotter Security Rules Schema
  description: OpenAPI schema specification for CEL-based Kubernetes security review rules
  version: 1.0.0

paths: {}

components:
  schemas:
    SecurityRule:
      type: object
      required:
        - apiVersion
        - kind
        - metadata
        - spec
      properties:
        apiVersion:
          type: string
          enum:
            - rules.spotter.run/v1
          description: API version of the rule
        kind:
          type: string
          enum:
            - SecurityRule
          description: Kind of the resource
        metadata:
          $ref: '#/components/schemas/RuleMetadata'
        spec:
          $ref: '#/components/schemas/RuleSpec'

    RuleMetadata:
      type: object
      required:
        - name
      properties:
        name:
          type: string
          pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
          minLength: 1
          maxLength: 253
          description: Unique name of the rule
        labels:
          type: object
          additionalProperties:
            type: string
          description: Labels for categorizing and organizing rules

    RuleSpec:
      type: object
      required:
        - id
        - name
        - version
        - description
        - severity
        - category
        - match
        - cel
      properties:
        id:
          type: string
          pattern: '^SPOTTER-[A-Z-]+-[0-9]{3}$'
          description: Unique identifier for the rule
          example: SPOTTER-CONTAINER-SECURITY-001
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: Human-readable name of the rule
        version:
          type: string
          pattern: '^\d+\.\d+\.\d+$'
          description: Semantic version of the rule
          example: "1.0.0"
        description:
          type: string
          minLength: 1
          maxLength: 1000
          description: Detailed explanation of what this rule checks
        severity:
          $ref: '#/components/schemas/Severity'
        category:
          type: string
          enum:
            - "Workload Security"
            - "Access Control"
            - "Network & Traffic Security"
            - "Secrets & Data Protection"
            - "Configuration & Resource Hygiene"
            - "Supply Chain & Image Security"
            - "CI/CD & GitOps Security"
            - "Runtime Threat Detection"
            - "Audit, Logging & Compliance"
            - "Platform & Infrastructure Security"
          description: Primary category of the security rule (10 abstracted categories covering comprehensive K8s and cloud security)
        subcategory:
          type: string
          maxLength: 100
          description: More specific categorization within the main category
        cwe:
          type: string
          pattern: '^CWE-\d+$'
          description: Common Weakness Enumeration identifier
          example: "CWE-269"
        regulatoryStandards:
          type: array
          items:
            $ref: '#/components/schemas/RegulatoryStandard'
          description: Regulatory standards this rule helps comply with
        match:
          $ref: '#/components/schemas/MatchCriteria'
        cel:
          type: string
          minLength: 1
          description: CEL (Common Expression Language) expression for rule evaluation
        remediation:
          $ref: '#/components/schemas/Remediation'
        references:
          type: array
          items:
            $ref: '#/components/schemas/Reference'
          description: External references and documentation
        metadata:
          $ref: '#/components/schemas/RuleAdditionalMetadata'

    Severity:
      type: object
      required:
        - level
        - score
      properties:
        level:
          $ref: '#/components/schemas/SeverityLevel'
        score:
          type: number
          minimum: 0.0
          maximum: 10.0
          multipleOf: 0.1
          description: CVSS-like risk score from 0.0 to 10.0

    SeverityLevel:
      type: string
      enum:
        - LOW
        - MEDIUM
        - HIGH
        - CRITICAL
      description: Severity level of the security rule

    RegulatoryStandard:
      type: object
      required:
        - name
        - reference
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 200
          description: Name of the regulatory standard
        reference:
          type: string
          format: uri
          description: URL reference to the standard documentation

    MatchCriteria:
      type: object
      required:
        - resources
      properties:
        resources:
          $ref: '#/components/schemas/ResourceCriteria'

    ResourceCriteria:
      type: object
      required:
        - kubernetes
      properties:
        kubernetes:
          $ref: '#/components/schemas/KubernetesResourceCriteria'

    KubernetesResourceCriteria:
      type: object
      required:
        - apiGroups
        - versions
        - kinds
      properties:
        apiGroups:
          type: array
          items:
            type: string
          minItems: 1
          description: Kubernetes API groups to match
          example: ["", "apps", "extensions"]
        versions:
          type: array
          items:
            type: string
          minItems: 1
          description: API versions to match
          example: ["v1", "v1beta1"]
        kinds:
          type: array
          items:
            type: string
          minItems: 1
          description: Kubernetes resource kinds to match
          example: ["Pod", "Deployment", "StatefulSet"]
        namespaces:
          $ref: '#/components/schemas/NamespaceSelector'
        labels:
          $ref: '#/components/schemas/LabelSelector'

    NamespaceSelector:
      type: object
      properties:
        include:
          type: array
          items:
            type: string
          description: Namespaces to include (supports wildcards)
          example: ["*", "production-*"]
        exclude:
          type: array
          items:
            type: string
          description: Namespaces to exclude
          example: ["kube-system", "kube-public"]

    LabelSelector:
      type: object
      properties:
        include:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Labels that must be present with specified values
        exclude:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
          description: Labels that must not be present with specified values

    Remediation:
      type: object
      properties:
        manual:
          type: string
          description: Manual remediation steps

    Reference:
      type: object
      required:
        - title
        - url
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Title of the reference
        url:
          type: string
          format: uri
          description: URL to the reference
        description:
          type: string
          maxLength: 500
          description: Optional description of the reference

    RuleAdditionalMetadata:
      type: object
      properties:
        author:
          type: string
          maxLength: 100
          description: Author of the rule
        created:
          type: string
          format: date
          description: Creation date of the rule