apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: encryption-provider-not-properly-configured
  labels:
    category: "Secrets & Data Protection"
    severity: critical
spec:
  id: SPOTTER-SECRETS-DATA-PROTECTION-100
  name: "Encryption Provider Not Properly Configured"
  version: "1.0.0"
  description: "The API server should be configured with an encryption provider to encrypt sensitive data at rest in Etcd."
  severity:
    level: CRITICAL
    score: 9.5
  category: "Secrets & Data Protection"
  subcategory: "Data Encryption"
  cwe: "CWE-311"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "SC-28"
  match:
    resources:
      kubernetes:
        apiGroups:
          - "apiserver.config.k8s.io"
        versions:
          - v1
        kinds:
          - EncryptionConfiguration
  cel: |
    object.kind == "EncryptionConfiguration" &&
    has(object.resources) && object.resources.exists(res,
      has(res.resources) && res.resources.exists(r, r == "secrets") &&
      has(res.providers) && (
        size(res.providers) <= 2 ||
        !res.providers.exists(p, has(p.aescbc)) ||
        !res.providers.exists(p, has(p.secretbox))
      )
    )
  remediation:
    manual: "Configure the API server with an encryption provider by setting the `--encryption-provider-config` flag."
  references:
    - title: "Encrypting Secret Data at Rest"
      url: "https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"
