apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: root-container-not-mounted-read-only
  labels:
    category: "Workload Security"
    severity: high
spec:
  id: SPOTTER-WORKLOAD-SECURITY-112
  name: "Root Container Not Mounted Read-only"
  version: "1.0.0"
  description: "Containers running as root should have their root filesystem mounted as read-only to prevent unauthorized writes."
  severity:
    level: HIGH
    score: 8.0
  category: "Workload Security"
  subcategory: "Pod Security Context"
  cwe: "CWE-269"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.2.6"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - "apps"
        versions:
          - "v1"
        kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    (object.kind == 'Pod' && has(object.spec.containers) && object.spec.containers.exists(c, has(c.securityContext) && has(c.securityContext.runAsUser) && c.securityContext.runAsUser == 0 && (!has(c.securityContext.readOnlyRootFilesystem) || c.securityContext.readOnlyRootFilesystem == false))) || (object.kind != 'Pod' && has(object.spec.template.spec.containers) && object.spec.template.spec.containers.exists(c, has(c.securityContext) && has(c.securityContext.runAsUser) && c.securityContext.runAsUser == 0 && (!has(c.securityContext.readOnlyRootFilesystem) || c.securityContext.readOnlyRootFilesystem == false)))
  remediation:
    manual: "Set `readOnlyRootFilesystem: true` for containers running as root."
  references:
    - title: "Kubernetes Pod Security Standards (Restricted)"
      url: "https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"
