# GoReleaser configuration for Spotter
version: 2

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/madhuakula/spotter/pkg/version.Version={{.Version}}
      - -X github.com/madhuakula/spotter/pkg/version.CommitHash={{.Commit}}
      - -X github.com/madhuakula/spotter/pkg/version.BuildDate={{.Date}}
    binary: spotter

archives:
  - name_template: >
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'

dockers:
  # Multi-platform spotter image (CLI + admission controller)
  - image_templates:
      - "ghcr.io/madhuakula/spotter:{{ .Tag }}"
      - "ghcr.io/madhuakula/spotter:latest"
    dockerfile: Dockerfile
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64,linux/arm64"
      - "--build-arg=VERSION={{.Version}}"
      - "--build-arg=COMMIT={{.FullCommit}}"
      - "--build-arg=DATE={{.Date}}"
      - "--build-arg=ENABLE_VERSIONING=true"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--label=org.opencontainers.image.source={{.GitURL}}"
      - "--label=org.opencontainers.image.description=Spotter - Kubernetes security scanner and admission controller"
    extra_files:
      - go.mod
      - go.sum
      - main.go
      - cmd/
      - pkg/

release:
  github:
    owner: madhuakula
    name: spotter
  draft: false
  prerelease: auto
  name_template: "{{.ProjectName}} v{{.Version}}"
