---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: spotter-validating-webhook
  labels:
    app: spotter
webhooks:
- name: security.spotter.io
  clientConfig:
    service:
      name: spotter-admission-controller
      namespace: spotter-system
      path: "/admit"
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCekNDQWUrZ0F3SUJBZ0lVYytBbndqV0JaYmVmK1NCTEhVS0NGZThwQXFRd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0V6RVJNQThHQTFVRUF3d0lURzlqWVd3dFEwRXdIaGNOTWpVd09EQXhNVGt5TWpRd1doY05Nall3T0RBeApNVGt5TWpRd1dqQVRNUkV3RHdZRFZRUUREQWhNYjJOaGJDMURRVENDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTHNpNmF2SlhXdW1KMlVBemg2aEVMUkQzbWZscTBxRWE0Zkh5dFZvS0poaEZiZWYKNjFocVBpdUFzL0llY2FRT0dYakh6c1ZBSHprS2VGRXVoejhKUzhwUDFSRXFlZHY3N21lbEJFWUdVM3J1cDV0UApESG9DcjREcE1jbUF4KzZmdi9KNGJRQTBUak93ZUVsZ2FHV1YvcEJ0dmNlRnJMWGlqOHBIOUZBbEEybzJVVGNECmZka2hXbzBNazczVDMvbG40LzhtRm5hSUw5OHBJWWZFOFc5ME5tYTcwK08rQkN0ZEVGSW5kRDMrQzhseTVJbWwKd3ZTdk5YZE9QQlFONEZPQU5kcGJmOU9ndHR2WS9PZWFiakZGYU84WjRqNXFMVEZCMVVwR0tHS21tNHBpQXN0YwpSUlFkaHJqNzBoMlU4YW1OUkxXbHpLVS9JZlJEYmFVTDVsVmRGTWNDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFCkZNRUNQZHVrcVJEak5ydThVM0JodGFuQmoyZ29NQjhHQTFVZEl3UVlNQmFBRk1FQ1BkdWtxUkRqTnJ1OFUzQmgKdGFuQmoyZ29NQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBS0NOVTdjRwphY2JUSndwYkh1Zk5aTlhTWm9CRXFUTHVpYjZvdW1DNWowa2NYb3Q1TEVBNkhEZUlXS1pqbVlqQjFsbldFTFM0CmE2SFFOeVpCbWxxTHB1TjQ4QURCbkExN0hITW5CS20rNTRNNUViY0xmSDZqczlPR01mTTIrMDdxdTU0ZGxtVFMKUWxoYWxycWpVWVRDYmlwdUloWXQxWXpjdEFaNHNsNXJ4VytMaTRsSFlhbk1UNFZOS3YvZlJJY1dmM2xGQ3FicwpCM0xDNXhRUHJvUWcwMlR1dlhTNDR3U1lQL0FtbEd3ano4R0hKcC9odit5QjRPYk5YdE0xcW9yQ0lmNlpRZU1GCklqaDJkL3RmT1MwZVhvVzBHRzg3RGxtSjc5ZG5Dc0pCcHpsbXUzc3h1MmpUcGNQUDNjdjVuUHdSdm15NjZCNE4KYXZ6YUJpdlIrdDRpd3JBPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  # Only validate CREATE operations, not updates
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  - operations: ["CREATE"]
    apiGroups: ["apps"]
    apiVersions: ["v1"]
    resources: ["deployments", "replicasets", "daemonsets", "statefulsets"]
  - operations: ["CREATE"]
    apiGroups: ["batch"]
    apiVersions: ["v1"]
    resources: ["jobs", "cronjobs"]
  # any extra CRDs can be added here
  namespaceSelector:
    matchExpressions:
    - key: name
      operator: NotIn
      values: ["kube-system", "kube-public", "kube-node-lease", "spotter-system", "local-path-storage"]
  admissionReviewVersions: ["v1", "v1beta1"]
  sideEffects: None
  failurePolicy: Fail  # More lenient for local testing
  timeoutSeconds: 10
