apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: net-raw-capabilities-not-being-dropped
  labels:
    category: "Workload Security"
    severity: high
spec:
  id: SPOTTER-WORKLOAD-SECURITY-306
  name: "NET_RAW Capabilities Not Being Dropped"
  version: "1.0.0"
  description: "NET_RAW capability must be dropped"
  severity:
    level: HIGH
    score: 8.0
  category: "Workload Security"
  subcategory: "Container Capabilities"
  cwe: "CWE-306"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.2.11"
  match:
    resources:
      kubernetes:
        apiGroups:
        - ''
        - apps
        versions:
        - v1
        kinds:
        - Pod
        - Deployment
        - StatefulSet
        namespaces:
          include:
          - '*'
          exclude:
          - kube-system
          - kube-public
  cel: |
    (object.kind == 'Pod' && has(object.spec.containers) && object.spec.containers.exists(c, has(c.securityContext) && has(c.securityContext.capabilities) && has(c.securityContext.capabilities.add) && c.securityContext.capabilities.add.exists(cap, cap == "NET_RAW"))) ||
    (object.kind != 'Pod' && has(object.spec.template.spec.containers) && object.spec.template.spec.containers.exists(c, has(c.securityContext) && has(c.securityContext.capabilities) && has(c.securityContext.capabilities.add) && c.securityContext.capabilities.add.exists(cap, cap == "NET_RAW")))
  remediation:
    manual: "Drop NET_RAW capability in securityContext"
  metadata:
    author: "Spotter AutoGen"
    created: "2025-07-29"
