apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: workload-mounting-with-sensitive-os-directory
  labels:
    category: "Workload Security"
    severity: critical
spec:
  id: SPOTTER-WORKLOAD-SECURITY-108
  name: "Workload Mounting With Sensitive OS Directory"
  version: "1.0.0"
  description: "Workloads should not mount sensitive host directories (e.g., `/etc`, `/var`, `/usr`) with write permissions, as this can lead to privilege escalation or system compromise."
  severity:
    level: CRITICAL
    score: 9.0
  category: "Workload Security"
  subcategory: "Volume Mounts"
  cwe: "CWE-269"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.2.5"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - "apps"
        versions:
          - "v1"
        kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    ((object.kind == 'Pod' && has(object.spec.volumes) && object.spec.volumes.exists(v, has(v.hostPath) && (v.hostPath.path.startsWith('/etc') || v.hostPath.path.startsWith('/var') || v.hostPath.path.startsWith('/usr')))) || (object.kind != 'Pod' && has(object.spec.template.spec.volumes) && object.spec.template.spec.volumes.exists(v, has(v.hostPath) && (v.hostPath.path.startsWith('/etc') || v.hostPath.path.startsWith('/var') || v.hostPath.path.startsWith('/usr')))))
  remediation:
    manual: "Avoid mounting sensitive host directories. If necessary, ensure they are mounted as read-only by setting `readOnly: true` in the volume mount."
  references:
    - title: "Kubernetes Volumes"
      url: "https://kubernetes.io/docs/concepts/storage/volumes/#hostpath"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"