apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: incorrect-volume-claim-access-mode-readwriteonce
  labels:
    category: "Configuration & Resource Hygiene"
    severity: low
spec:
  id: SPOTTER-CONFIGURATION-RESOURCE-HYGIENE-103
  name: "Incorrect Volume Claim Access Mode ReadWriteOnce"
  version: "1.0.0"
  description: "PersistentVolumeClaims with `ReadWriteOnce` access mode can only be mounted by a single node. Ensure this is appropriate for your workload, especially in multi-replica deployments."
  severity:
    level: LOW
    score: 3.0
  category: "Configuration & Resource Hygiene"
  subcategory: "Storage Configuration"
  cwe: "CWE-665"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "CM-6"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - apps
        versions:
          - v1
        kinds:
          - PersistentVolumeClaim
          - StatefulSet
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    (object.kind == "PersistentVolumeClaim" && has(object.spec.accessModes) && object.spec.accessModes.exists(mode, mode == "ReadWriteOnce")) ||
    (object.kind == "StatefulSet" && has(object.spec.volumeClaimTemplates) && object.spec.volumeClaimTemplates.exists(vct, has(vct.spec.accessModes) && vct.spec.accessModes.exists(mode, mode == "ReadWriteOnce")))
  remediation:
    manual: "If shared access is required for multiple pods or nodes, consider using `ReadWriteMany` or `ReadOnlyMany` access modes for your PersistentVolumeClaim, if supported by your storage provisioner."
  references:
    - title: "Kubernetes Persistent Volumes"
      url: "https://kubernetes.io/docs/concepts/storage/persistent-volumes/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"
