apiVersion: rules.spotter.dev/v1alpha1
kind: SpotterRulePack
metadata:
  name: spotter-nist-800-53-pack
  annotations:
    rules.spotter.dev/title: "NIST 800-53"
    rules.spotter.dev/version: "1.0.0"
    rules.spotter.dev/author: "Spotter Security Team"
    rules.spotter.dev/description: "Implements NIST 800-53 controls."
spec:
  rules:
    - spotter-workload-001
    - spotter-platform-001
    - spotter-network-002
  references:
    - title: "NIST 800-53"
      url: "https://www.nist.gov/800-53"
