apiVersion: rules.spotter.dev/v1alpha1
kind: SpotterRulePack
metadata:
  name: spotter-cis-kubernetes-benchmark-pack
  annotations:
    rules.spotter.dev/title: "CIS Kubernetes Benchmark v1.30 Rule Pack"
    rules.spotter.dev/version: "1.0.0"
    rules.spotter.dev/author: "Spotter Security Team"
    rules.spotter.dev/description: "Implements CIS Kubernetes Benchmark controls for v1.30."
spec:
  rules:
    - spotter-workload-001
    - spotter-platform-001
    - spotter-network-002
  references:
    - title: "CIS Kubernetes Benchmark"
      url: "https://www.cisecurity.org/benchmark/kubernetes"
