apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: cluster-admin-rolebinding-with-superuser-permissions
  labels:
    category: "Access Control"
    severity: critical
spec:
  id: SPOTTER-ACCESS-CONTROL-994
  name: "Cluster Admin Rolebinding With Superuser Permissions"
  version: "1.0.0"
  description: "The `cluster-admin` role should not be bound to regular users or groups, as it provides unrestricted superuser access to the cluster."
  severity:
    level: CRITICAL
    score: 9.8
  category: "Access Control"
  subcategory: "Authorization"
  cwe: "CWE-266"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.1.1"
  match:
    resources:
      kubernetes:
        apiGroups:
          - "rbac.authorization.k8s.io"
        versions:
          - "v1"
          - "v1beta1"
        kinds:
          - ClusterRoleBinding
  cel: |
    has(object.roleRef) && object.roleRef.kind == "ClusterRole" && object.roleRef.name == "cluster-admin" &&
    has(object.subjects) && object.subjects.exists(s, s.kind in ["User", "Group", "ServiceAccount"])
  remediation:
    manual: "Avoid binding the `cluster-admin` role to users or groups. Use more specific roles and role bindings to grant only the necessary permissions."
  references:
    - title: "Using RBAC Authorization"
      url: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-30"
