apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: namespace-lifecycle-admission-control-plugin-disabled
  labels:
    category: "Access Control"
    severity: high
spec:
  id: SPOTTER-ACCESS-CONTROL-522
  name: "Namespace Lifecycle Admission Control Plugin Disabled"
  version: "1.0.0"
  description: "NamespaceLifecycle plugin must be enabled"
  severity:
    level: HIGH
    score: 8.0
  category: "Access Control"
  subcategory: "Admission Control"
  cwe: "CWE-284"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "1.2.14"
  match:
    resources:
      kubernetes:
        apiGroups:
        - ""
        - "kubeadm.k8s.io"
        versions:
        - v1
        - v1beta3
        kinds:
        - Pod
        - ClusterConfiguration
  cel: |
    (object.kind == "Pod" && has(object.spec.containers) && object.spec.containers.exists(c,
      has(c.command) && c.command.exists(cmd, cmd == "kube-apiserver") &&
      (
        (has(c.args) && c.args.exists(arg, arg.contains("--disable-admission-plugins=") && arg.contains("NamespaceLifecycle"))) ||
        (has(c.command) && c.command.exists(cmd, cmd.contains("--disable-admission-plugins=") && cmd.contains("NamespaceLifecycle")))
      )
    )) || (object.kind == "ClusterConfiguration" && has(object.apiServer.disableAdmissionPlugins) && ("NamespaceLifecycle" in object.apiServer.disableAdmissionPlugins))
  remediation:
    manual: "Enable NamespaceLifecycle admission plugin"
  metadata:
    author: "Spotter AutoGen"
    created: "2025-07-29"
