apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: service-account-admission-control-plugin-disabled
  labels:
    category: "Access Control"
    severity: high
spec:
  id: SPOTTER-ACCESS-CONTROL-106
  name: "Service Account Admission Control Plugin Disabled"
  version: "1.0.0"
  description: "The `ServiceAccount` admission controller should be enabled to ensure service accounts are properly managed."
  severity:
    level: HIGH
    score: 8.0
  category: "Access Control"
  subcategory: "Admission Control"
  cwe: "CWE-284"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "1.2.18"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
        versions:
          - v1
        kinds:
          - Pod
        namespaces:
          include: ["kube-system"]
          exclude: ["*"]
  cel: |
    has(object.spec.containers) && object.spec.containers.exists(c, has(c.command) && c.command.exists(cmd, cmd == "kube-apiserver") && has(c.args) && !c.args.exists(arg, arg.contains("--enable-admission-plugins=") && arg.contains("ServiceAccount")))
  remediation:
    manual: "Enable the `ServiceAccount` admission plugin in the kube-apiserver configuration."
  references:
    - title: "Kubernetes Admission Controllers"
      url: "https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#serviceaccount"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"
