# Spotter Default Configuration
# This is the default configuration file for Spotter

# Hub configuration
hub_url: "https://rules.spotter.run/api/v1"
api_key: ""
cache_dir: "~/.spotter"
rules_dir: "~/.spotter/rules"
packs_dir: "~/.spotter/rulepacks"

# Logging configuration
logging:
  level: "info"
  format: "text"

# Rules configuration
rules:
  custom_paths:
    - "./custom-rules/"
    - "/etc/spotter/rules/"
  severity_filter:
    - "CRITICAL"
    - "HIGH"
    - "MEDIUM"
    - "LOW"
  min_severity: ""
  include_rules: []
  exclude_rules: []
  categories: []
  custom_filters: {}
  default_packs:
    - "spotter-secure-defaults-pack"

# Output configuration
output:
  format: "table"
  verbose: false
  file: ""
  pretty: true

# Kubernetes configuration
kubernetes:
  kubeconfig: "~/.kube/config"
  context: ""
  timeout: "30s"
  namespace: ""

# Helm configuration
helm:
  release_name: "spotter-scan"
  namespace: "default"
  kube_version: ""
  values_files: []
  set_values: []
  set_string_values: []
  skip_crds: false
  skip_tests: false
  validate_schema: false
  include_crds: true
  update_dependencies: false
  chart_repo: ""
  chart_version: ""