apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: cni-plugin-does-not-support-network-policies
  labels:
    category: "Network & Traffic Security"
    severity: high
spec:
  id: SPOTTER-NETWORK-TRAFFIC-SECURITY-101
  name: "CNI Plugin Does Not Support Network Policies"
  version: "1.0.0"
  description: "The CNI plugin in use should support network policies to enforce network segmentation."
  severity:
    level: HIGH
    score: 8.0
  category: "Network & Traffic Security"
  subcategory: "NetworkPolicy"
  cwe: "CWE-665"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "4.5.1"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
        versions:
          - "v1"
        kinds:
          - ConfigMap
        namespaces:
          include: ["*"]
          exclude: []
  cel: |
    object.kind == "ConfigMap" &&
    has(object.data) &&
    (
      (has(object.data["cni-conf.json"]) &&
       object.data["cni-conf.json"].contains('"type": "flannel"')) ||
      (has(object.data["net-conf.json"]) &&
       object.metadata.labels.app == "flannel")
    ) &&
    !(
      (has(object.data["cni-conf.json"]) &&
       (object.data["cni-conf.json"].contains('"type": "calico"') ||
        object.data["cni-conf.json"].contains('"type": "cilium"') ||
        object.data["cni-conf.json"].contains('"type": "weave"'))) ||
      (object.metadata.labels.app in ["calico", "cilium", "weave"])
    )
  remediation:
    manual: "Ensure that the CNI plugin used in the cluster supports and enforces network policies. Examples of such plugins include Calico, Cilium, and Weave Net."
  references:
    - title: "Kubernetes Network Policies"
      url: "https://kubernetes.io/docs/concepts/services-networking/network-policies/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-30"
