apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: ingress-controller-exposes-workload
  labels:
    category: "Network & Traffic Security"
    severity: high
spec:
  id: SPOTTER-NETWORK-TRAFFIC-SECURITY-001
  name: "Ingress Controller Exposes Workload"
  version: "1.0.0"
  description: "An Ingress Controller exposes a workload by referencing an existing service backend, which may be unintentional."
  severity:
    level: HIGH
    score: 7.4
  category: "Network & Traffic Security"
  subcategory: "Ingress"
  cwe: "CWE-319"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "SC-8"
  match:
    resources:
      kubernetes:
        apiGroups:
          - "networking.k8s.io"
        versions:
          - "v1"
        kinds:
          - Ingress
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    object.kind == "Ingress" &&
    has(object.spec.rules) &&
    object.spec.rules.exists(rule,
      has(rule.http) && has(rule.http.paths) &&
      rule.http.paths.exists(path,
        has(path.backend) && has(path.backend.serviceName) &&
        path.backend.serviceName == "app"
      )
    )
  remediation:
    manual: "Review the Ingress configuration to ensure it only exposes intended services. Consider using more specific service names or implementing proper access controls."
  references:
    - title: "Kubernetes Ingress"
      url: "https://kubernetes.io/docs/concepts/services-networking/ingress"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
