- name: insecure sample 1 should fail
  pass: false
  input: |
    apiVersion: v1
    kind: Service
    metadata:
      name: app
      labels:
        app: app
    spec:
      type: ClusterIP
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        app: app
    
    
    ---
    
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: app-ingress
      annotations:
        kubernetes.io/ingress.class: "nginx"
      labels:
        app: app
    spec:
      rules:
      - host: app.acme.org
        http:
          paths:
          - backend:
              serviceName: app
              servicePort: 3000

- name: secure sample 1 should pass
  pass: true
  input: |
    apiVersion: v1
    kind: Service
    metadata:
      name: app
      labels:
        app: app
    spec:
      type: ClusterIP
      ports:
      - port: 3000
        targetPort: 3000
      selector:
        app: app
    
    
    ---
    
    apiVersion: extensions/v1beta1
    kind: Ingress
    metadata:
      name: app-ingress
      annotations:
        kubernetes.io/ingress.class: "nginx"
      labels:
        app: app
    spec:
      rules:
      - host: app.acme.org
        http:
          paths:
          - backend:
              serviceName: app2
              servicePort: 3000
