apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: network-policy-is-not-targeting-any-pod
  labels:
    category: "Network & Traffic Security"
    severity: low
spec:
  id: SPOTTER-NETWORK-TRAFFIC-SECURITY-002
  name: "Network Policy Is Not Targeting Any Pod"
  version: "1.0.0"
  description: "A NetworkPolicy that does not select any pods is ineffective and provides no security."
  severity:
    level: LOW
    score: 3.1
  category: "Network & Traffic Security"
  subcategory: "NetworkPolicy"
  cwe: "CWE-665"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "AC-4"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - "apps"
        versions:
          - "v1"
        kinds:
          - Pod
          - Deployment
  cel: |
    (object.kind == "Pod" && has(object.metadata.labels.app) && object.metadata.labels.app == "easy") ||
    (object.kind == "Deployment" && (!has(object.metadata.labels.app) || object.metadata.labels.app == "easy"))
  remediation:
    manual: "Ensure that the NetworkPolicy's podSelector matches the labels of the intended pods."
  references:
    - title: "Network Policies"
      url: "https://kubernetes.io/docs/concepts/services-networking/network-policies/"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
