- name: insecure sample 1 should fail
  pass: false
  input: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: positive2-pod
      namespace: positive2
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

- name: insecure sample 2 should fail
  pass: false
  input: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: positive1-pod
      namespace: positive1-one
      labels:
        app: shouldmatch
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80

- name: secure sample 1 should pass
  pass: true
  input: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: negative1-pod
      namespace: negative1
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: app
        image: images.my-company.example/app:v4
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

- name: secure sample 2 should pass
  pass: true
  input: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: negative2-pod
      namespace: negative2-namespace
      labels:
        app: negative2-app
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - name: app
        image: images.my-company.example/app:v4
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"

- name: secure sample 3 should pass
  pass: true
  input: |
    apiVersion: v1
    kind: Pod
    metadata:
      name: negative3-pod
      namespace: negative3
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
