apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: service-type-is-nodeport
  labels:
    category: "Network & Traffic Security"
    severity: medium
spec:
  id: SPOTTER-NETWORK-TRAFFIC-SECURITY-004
  name: "Service Exposed via NodePort"
  version: "1.0.0"
  description: "Services of type NodePort are exposed on each node's IP at a static port. This can be a security risk if not properly managed."
  severity:
    level: MEDIUM
    score: 6.1
  category: "Network & Traffic Security"
  subcategory: "Service"
  cwe: "CWE-501"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "AC-4"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
        versions:
          - "v1"
        kinds:
          - Service
  cel: |
    has(object.spec.type) && object.spec.type == "NodePort"
  remediation:
    manual: "If the service is not intended to be exposed directly on the node, consider using a different service type like ClusterIP."
  references:
    - title: "Kubernetes Service Types"
      url: "https://kubernetes.io/docs/concepts/services-networking/service/#publishing-services-service-types"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
