apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: service-does-not-target-pod
  labels:
    category: "Network & Traffic Security"
    severity: low
spec:
  id: SPOTTER-NETWORK-TRAFFIC-SECURITY-100
  name: "Service Does Not Target Pod"
  version: "1.0.0"
  description: "A Kubernetes Service should target at least one pod to be functional. A service without a matching pod selector is ineffective."
  severity:
    level: LOW
    score: 3.0
  category: "Network & Traffic Security"
  subcategory: "Service Configuration"
  cwe: "CWE-665"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "CM-6"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
        versions:
          - v1
        kinds:
          - Service
  cel: |
    object.kind == "Service" && (!has(object.spec.selector) || size(object.spec.selector) == 0)
  remediation:
    manual: "Ensure that the Service's `spec.selector` matches the labels of existing pods."
  references:
    - title: "Kubernetes Services"
      url: "https://kubernetes.io/docs/concepts/services-networking/service/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"
