apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: rbac-clusteradmin-binding
  labels:
    category: "Access Control"
    severity: high
spec:
  id: SPOTTER-ACCESS-CONTROL-004
  name: "Excessive Cluster-Admin Role Bindings"
  version: "1.0.0"
  description: "The cluster-admin role provides unrestricted access to the cluster. Its use should be limited to the bare minimum."
  severity:
    level: HIGH
    score: 8.1
  category: "Access Control"
  subcategory: "Authorization"
  cwe: "CWE-266"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.1.1"
  match:
    resources:
      kubernetes:
        apiGroups:
          - "rbac.authorization.k8s.io"
        versions:
          - "v1"
        kinds:
          - ClusterRoleBinding
        namespaces:
          include: ["*"]
          exclude: []
  cel: |
    has(object.roleRef) && object.roleRef.apiGroup == "rbac.authorization.k8s.io" && object.roleRef.kind == "ClusterRole" && object.roleRef.name == "cluster-admin" &&
    has(object.subjects) && object.subjects.exists(s, s.kind == "User" || s.kind == "Group")
  remediation:
    manual: "Review all ClusterRoleBindings that grant the cluster-admin role. Remove any bindings that are not absolutely necessary."
  references:
    - title: "Using RBAC Authorization"
      url: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
