apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: rbac-role-allows-secrets-read
  labels:
    category: "Access Control"
    severity: high
spec:
  id: SPOTTER-ACCESS-CONTROL-006
  name: "RBAC Role Allows Reading Secrets"
  version: "1.0.0"
  description: "Roles that allow reading secrets can expose sensitive information and should be tightly controlled."
  severity:
    level: HIGH
    score: 8.2
  category: "Access Control"
  subcategory: "Authorization"
  cwe: "CWE-200"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "AC-3"
  match:
    resources:
      kubernetes:
        apiGroups:
          - "rbac.authorization.k8s.io"
        versions:
          - "v1"
        kinds:
          - Role
          - ClusterRole
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    has(object.rules) && object.rules.exists(r, 
      has(r.resources) && r.resources.exists(res, res == "secrets") &&
      has(r.verbs) && (r.verbs.exists(v, v == "get") || r.verbs.exists(v, v == "list") || r.verbs.exists(v, v == "watch"))
    )
  remediation:
    manual: "Review the role and remove permissions to read secrets if not absolutely necessary."
  references:
    - title: "Kubernetes RBAC - Secrets"
      url: "https://kubernetes.io/docs/concepts/configuration/secret/"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
