apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: rbac-role-allows-impersonate
  labels:
    category: "Access Control"
    severity: high
spec:
  id: SPOTTER-ACCESS-CONTROL-005
  name: "RBAC Role Allows Impersonation"
  version: "1.0.0"
  description: "The 'impersonate' verb in RBAC allows a user to act as another user, which can be a significant security risk."
  severity:
    level: HIGH
    score: 8.7
  category: "Access Control"
  subcategory: "Authorization"
  cwe: "CWE-266"
  regulatoryStandards:
    - name: "NIST SP 800-53"
      reference: "https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final"
      section: "AC-6"
  match:
    resources:
      kubernetes:
        apiGroups:
          - "rbac.authorization.k8s.io"
        versions:
          - "v1"
        kinds:
          - Role
          - ClusterRole
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    has(object.rules) && object.rules.exists(r, has(r.verbs) && r.verbs.exists(v, v == "impersonate"))
  remediation:
    manual: "Review the role and remove the 'impersonate' verb if it is not required."
  references:
    - title: "Kubernetes RBAC - Impersonation"
      url: "https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-impersonation"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
