apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: workload-uses-hostpath-volume
  labels:
    category: "Platform & Infrastructure Security"
    severity: high
spec:
  id: SPOTTER-PLATFORM-INFRASTRUCTURE-SECURITY-007
  name: "Workload Uses HostPath Volume"
  version: "1.0.0"
  description: "HostPath volumes mount a file or directory from the host node's filesystem into a pod. This can be a security risk if not managed carefully."
  severity:
    level: HIGH
    score: 8.3
  category: "Platform & Infrastructure Security"
  subcategory: "Pod Security"
  cwe: "CWE-668"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "5.2.5"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - "apps"
        versions:
          - "v1"
        kinds:
          - Pod
          - Deployment
          - StatefulSet
          - DaemonSet
        namespaces:
          include: ["*"]
          exclude: ["kube-system", "kube-public"]
  cel: |
    (object.kind == 'Pod' && has(object.spec.volumes) && object.spec.volumes.exists(v, has(v.hostPath))) ||
    (object.kind != 'Pod' && has(object.spec.template.spec.volumes) && object.spec.template.spec.volumes.exists(v, has(v.hostPath)))
  remediation:
    manual: "Avoid using HostPath volumes if possible. If they are required, ensure that they are read-only and restricted to specific directories."
  references:
    - title: "Volumes - hostPath"
      url: "https://kubernetes.io/docs/concepts/storage/volumes/#hostpath"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
