apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: audit-policy-file-not-defined
  labels:
    category: "Audit, Logging & Compliance"
    severity: high
spec:
  id: SPOTTER-AUDIT-100
  name: "Audit Policy File Not Defined"
  version: "1.0.0"
  description: "The API server should be configured with an audit policy file to define what events should be logged."
  severity:
    level: HIGH
    score: 7.5
  category: "Audit, Logging & Compliance"
  subcategory: "Auditing"
  cwe: "CWE-778"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "3.2.1"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
        versions:
          - v1
        kinds:
          - Pod
  cel: |
    has(object.spec.containers) && object.spec.containers.exists(c, has(c.command) && c.command.exists(cmd, cmd == "kube-apiserver") && (!has(c.args) || !c.args.exists(arg, arg.startsWith("--audit-policy-file="))))
  remediation:
    manual: "Configure the API server with an audit policy file by setting the `--audit-policy-file` flag."
  references:
    - title: "Kubernetes Auditing"
      url: "https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/"
  metadata:
    author: "Spotter Security Team"
    created: "2025-07-29"
