apiVersion: rules.spotter.run/v1
kind: SecurityRule
metadata:
  name: audit-log-maxage-not-properly-set
  labels:
    category: "Audit, Logging & Compliance"
    severity: medium
spec:
  id: SPOTTER-AUDIT-004
  name: "Audit Log Maxage Not Properly Set"
  version: "1.0.0"
  description: "The maximum age of the audit log files is not set. This can lead to excessive disk usage."
  severity:
    level: MEDIUM
    score: 5.3
  category: "Audit, Logging & Compliance"
  subcategory: "Logging"
  cwe: "CWE-770"
  regulatoryStandards:
    - name: "CIS Kubernetes Benchmark v1.8.0"
      reference: "https://www.cisecurity.org/benchmark/kubernetes"
      section: "3.2.1"
  match:
    resources:
      kubernetes:
        apiGroups:
          - ""
          - serving.knative.dev
        versions:
          - v1
        kinds:
          - Pod
          - Configuration
          - Revision
  cel: |
    has(object.spec.containers) && object.spec.containers.exists(c,
      has(c.command) && c.command.exists(cmd, cmd == "kube-apiserver") &&
      (
        // Check if audit-log-maxage is not set in args or command, or is set to a value < 30
        (
          (!has(c.args) || !c.args.exists(arg, arg.startsWith("--audit-log-maxage="))) &&
          (!has(c.command) || !c.command.exists(cmd, cmd.startsWith("--audit-log-maxage=")))
        ) ||
        (
          has(c.args) && c.args.exists(arg, arg.startsWith("--audit-log-maxage=") && int(arg.split("=")[1]) < 30)
        ) ||
        (
          has(c.command) && c.command.exists(cmd, cmd.startsWith("--audit-log-maxage=") && int(cmd.split("=")[1]) < 30)
        )
      )
    )
  remediation:
    manual: "Edit the kube-apiserver pod specification file and add the --audit-log-maxage flag, setting it to a suitable value (e.g., 30)."
  references:
    - title: "Kubernetes Auditing"
      url: "https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/"
  metadata:
    author: "Spotter Security Team"
    created: "2024-07-29"
