- name: insecure sample 1 should fail
  pass: false
  input: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: helm
        name: tiller
      name: tiller-bad-args
    spec:
      selector:
        matchLabels:
          name: tiller
      template:
        metadata:
          labels:
            app: helm
            name: tiller
        spec:
          containers:
            -
              args:
                - "--listen=10.7.2.8:44134"
              image: tiller-image
              name: tiller-v2
              ports:
                -
                  containerPort: 44134
                  name: tiller
                  protocol: TCP
                -
                  containerPort: 44135
                  name: http
                  protocol: TCP
          serviceAccountName: tiller

- name: insecure sample 2 should fail
  pass: false
  input: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: helm
        name: tiller
      name: tiller-deploy-no-args
    spec:
      selector:
        matchLabels:
          name: tiller
      template:
        metadata:
          labels:
            app: helm
            name: tiller
        spec:
          containers:
            -
              name: tiller-v2
              image: tiller-image
          serviceAccountName: tiller

- name: secure sample 1 should pass
  pass: true
  input: |
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: tiller-deploy
      labels:
        app: helm
        name: tiller
    spec:
      selector:
        matchLabels:
          app: helm
          name: tiller
      template:
        metadata:
          labels:
            app: helm
            name: tiller
        spec:
          serviceAccountName: tiller
          containers:
            - name: tiller
              image: "tiller-image"
              args: ["--listen=127.0.0.1:44134"]
              ports:
              - containerPort: 44134
                name: tiller
                protocol: TCP
              - containerPort: 44135
                name: http
                protocol: TCP
